### ISSUE TITLE
Build inside a Docker container

### ISSUE THREAD

**Issue by venilnoronha** [envoyproxy/envoy-openssl#12]
The current Azure Pipeline [configuration](https://github.com/envoyproxy/envoy-openssl/blob/master/.azure-pipelines/linux.yaml) only runs the `verify` step. The `build` and `test` steps have been disabled as they reference dependencies incorrectly.

The right solution is to use the Envoy Docker CI image to run these steps. This again needs some work in getting the build to refer to the correct OpenSSL files.

**Comment by mythi** [comment]
> This again needs some work in getting the build to refer to the correct OpenSSL files.

I have this working. Will submit a PR later.
