### ISSUE TITLE
Add P&Z Support for Binaries/Images

### ISSUE THREAD

**Issue by Swapnali911** [envoyproxy/envoy-openssl#221]
As we are enabling support for P&Z architectures, could we include P&Z binaries/images alongside the x86 binaries in the releases? This will ensure that users on P&Z platforms can easily access and utilize the binaries.

**Request:**
Please add P&Z binaries/images to the releases page at https://github.com/envoyproxy/envoy-openssl/releases alongside x86 binaries.

**Benefit:**
Including P&Z binaries/images will improve accessibility for users on these platforms and ensure better support for a wider range of architectures.

Dependency : https://github.com/knative/infra/issues/344 

cc : @rishikakedia @valen-mascarenhas14 @ghatwala @dilipgb @NishikantThorat

**Comment by NishikantThorat** [comment]
@twghu / @tedjpoole/ @dcillera : Could you please guide us here?

**Comment by Swapnali911** [comment]
Looks like https://github.com/knative/infra/issues/344 is closed and they have moved to the downstream. So this requirement no longer required. Hence closing the issue.
